#!/bin/sh
#
# This is a really simple shell program that un-archives and "installs"
# some list packages that are required.
#
# This does not actually create or touch any files outside this elisp directory.
#

RUNEMACS=${RUNEMACS:-emacs}

COMPILEDIRS=" \
    bin
"
    # bin/elib-1.0 \
    # bin/speedbar-0.11 \
    # bin/semantic-1.2.1 \
    # bin/jde-2.2.4/lisp

LOADPATH=" \
    features \
    options \
    $COMPILEDIRS
"

cwd=`pwd`
if cygpath -w "$cwd" > /dev/null 2>&1 ; then
    cwd=`cygpath -w "$cwd" | sed 's/\\\\/\\\\\\\\/g'`
fi

echo "Generating elisp-dirs.el..."
rm -f elisp-dirs.el
echo ";;; Computer generated by install.sh.  Do not edit." > elisp-dirs.el
echo "(defvar elispdir \"$cwd\")" >> elisp-dirs.el
echo "(setq load-path" >> elisp-dirs.el
echo "      (append (list" >> elisp-dirs.el
for dir in $LOADPATH ; do
    echo "               \"$cwd/$dir\"" >> elisp-dirs.el
done
echo "               )" >> elisp-dirs.el
echo "              load-path))" >> elisp-dirs.el

# cd bin
# echo "Extracting Emacs Lisp library package..."
# gzip -dc elib.tar.gz | tar xf -
# echo "Extracting Speedbar..."
# gzip -dc speedbar.tar.gz | tar xf -
# echo "Extracting Semantic Bovinator..."
# gzip -dc semantic.tar.gz | tar xf -
# echo "Extracting Java Development Environment..."
# gzip -dc jde.tar.gz | tar xf -
# cd ..

echo "Compiling files..."
for dir in $COMPILEDIRS ; do
    echo "    $dir"
    $RUNEMACS -batch -l elisp-dirs.el -f batch-byte-compile $dir/*.el
done

echo "Done."
